language: python
python:
  - "3.9"
before_install:
  - sudo apt-get -y install python3-pip
  - sudo apt-get install python3.8-venv
install:
  - pip3 install -r requirements.txt
script:
  - coverage run manage.py test --keepdb
  - coverage report -m
after_success:
  - bash <(curl -s https://codecov.io/bash)