language: python
python:
  - "3.9"
before_install:
  - sudo apt-get -y install python3-pip
  - sudo apt-get -y install python3-venv
install:
  - pip3 install -r requirements.txt
script:
  - coverage run manage.py test --keepdb
  - coverage report -m
  - coverage html
  - ./codecov -t 9dae9e26-8a75-4ee0-acaa-49e4e4ec5d03
after_success:
  - bash <(curl -s https://codecov.io/bash)